const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let key='',offset=0,loading=false;const notes=new Map(),packages=new Map(),openNotes=new Set(),requests=new Map();
let magicToken=new URLSearchParams(location.hash.slice(1)).get('access');if(magicToken)history.replaceState(null,'',location.pathname);
const status=document.querySelector('#status'),list=document.querySelector('#leads');
async function call(url,options={}){const r=await fetch(url,{...options,headers:{Authorization:'Bearer '+key,...options.headers}});let d;try{d=await r.json();}catch{}if(!r.ok)throw new Error(d?.error||(r.status===401?'Open a fresh private link to sign in.':'The inbox could not be loaded. Try again.'));return d;}
const post=(url,data)=>call(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function packageText(r){return `${r.reply_to_person}\n\n${r.title}\n\n${r.deliverable}\n\nHOW TO USE THIS\n\n${r.how_to_use}`;}
function response(l){if(!l.result_json)return '';let r;try{r=JSON.parse(l.result_json);}catch{return '';}
 const text=packages.has(l.review_id)?packages.get(l.review_id):(l.edited_package??packageText(r));
 return `<section class="review-response"><p class="tag">Ready for your judgment</p><h3>${esc(r.title)}</h3><p class="note">This is a first version. Edit the package below, add your perspective, then copy it to share yourself.</p><label class="field" for="package-${l.review_id}">Their deliverable and your accompanying note</label><textarea id="package-${l.review_id}" class="response-editor" data-package="${l.review_id}" maxlength="12000">${esc(text)}</textarea><div class="actions"><button data-action="save-package" data-review="${l.review_id}">Save edits</button><button class="secondary" data-action="copy-package" data-review="${l.review_id}">Copy package</button></div><details><summary>Your review notes · kept out of the copied package</summary><h3>The opportunity</h3><p class="preserve">${esc(r.opportunity)}</p><h3>Your judgment matters here</h3><p class="preserve">${esc(r.human_judgment)}</p><h3>What would improve the next version</h3><p class="preserve">${esc(r.missing_information)}</p><h3>Notes used for this version</h3><p class="preserve">${esc(l.notes_snapshot||'No extra notes supplied.')}</p></details></section>`;
}
function card(l){let p={};try{p=JSON.parse(l.preview_json);}catch{}const busy=['pending','running'].includes(l.review_status);const note=notes.has(l.id)?notes.get(l.id):(l.owner_notes||'');
 return `<article class="admin-item" data-lead="${l.id}"><p class="note">${esc(new Date(l.created_at).toLocaleString())} · ${esc(l.channel)}</p><h2>${esc(l.name)}</h2>${l.email?`<p>${esc(l.email)}</p>`:'<p class="note">Friends route: no email collected.</p>'}<p class="quote">${esc(l.aim)}</p><p>AI experience: ${esc(l.experience)}. ${l.friction?'Difficulty: '+esc(l.friction):''}</p><p>Preview shown: ${esc(p.artifact)}</p><div class="actions"><button data-action="review" ${busy?'disabled':''}>${busy?'Review in progress':l.review_status==='ready'?'Submit again to Codex':'Submit to Codex'}</button><button class="secondary" data-action="notes">${note?'Edit notes':'Add notes'}</button></div><p class="note review-state">${l.review_status==='pending'?'Queued for Codex. Processing starts when Noah’s Mac is awake.':l.review_status==='running'?'Codex is preparing a deliverable and guidance for your review.':l.review_status==='ready'?'Response ready. You decide what goes back to the person.':l.review_status==='failed'?esc(l.review_error):'Submit the person’s idea as it is, or add your context first.'}</p><div class="owner-notes" ${openNotes.has(l.id)?'':'hidden'}><label class="field" for="notes-${l.id}">Your context and direction</label><textarea id="notes-${l.id}" data-notes="${l.id}" maxlength="4000" placeholder="What do you know about this person? What would make the result useful?">${esc(note)}</textarea><p class="note">Saving notes does not request a review. Submit to Codex includes the notes currently in this box.</p><button class="secondary" data-action="save-notes">Save notes</button></div><p class="item-status" role="status"></p>${response(l)}<details><summary>Submission details</summary>${l.notification_status?`<p class="note">Apple Messages: ${esc(l.notification_status)}${l.last_error?' · '+esc(l.last_error):''}</p>`:''}<label>Review status <select data-status="${l.id}">${['new','reviewing','follow-up','closed'].map(s=>`<option ${s===l.status?'selected':''}>${s}</option>`).join('')}</select></label><pre>${esc(JSON.stringify({id:l.id,preview:p},null,2))}</pre></details></article>`;
}
async function load(){if(loading)return;loading=true;try{const data=await call('/api/admin/leads?offset='+offset);document.querySelector('#login').hidden=true;document.querySelector('#inbox').hidden=false;document.querySelector('#key').value='';status.textContent='';document.querySelector('#previous').disabled=offset===0;document.querySelector('#next').disabled=!data.hasMore;list.innerHTML=data.leads.length?data.leads.map(card).join(''):'<p>No submissions yet.</p>';return true;}catch(e){status.textContent=e.message;return false;}finally{loading=false;}}
document.querySelector('#auth').addEventListener('submit',e=>{e.preventDefault();key=document.querySelector('#key').value;load();});document.querySelector('#refresh').onclick=load;
document.querySelector('#logout').onclick=async()=>{try{await post('/api/admin/logout',{});}catch(e){status.textContent=e.message;return;}key='';offset=0;notes.clear();packages.clear();openNotes.clear();requests.clear();list.innerHTML='';document.querySelector('#inbox').hidden=true;document.querySelector('#login').hidden=false;};
document.querySelector('#next').onclick=()=>{offset+=50;load();};document.querySelector('#previous').onclick=()=>{offset=Math.max(0,offset-50);load();};
list.addEventListener('input',e=>{if(e.target.dataset.notes)notes.set(e.target.dataset.notes,e.target.value);if(e.target.dataset.package)packages.set(e.target.dataset.package,e.target.value);});
list.addEventListener('change',async e=>{if(!e.target.dataset.status)return;try{await call('/api/admin/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:e.target.dataset.status,status:e.target.value})});status.textContent='Review status saved.';}catch(err){status.textContent=err.message;}});
list.addEventListener('click',async e=>{const button=e.target.closest('button[data-action]');if(!button)return;const article=button.closest('[data-lead]'),id=article.dataset.lead,feedback=article.querySelector('.item-status');const action=button.dataset.action;
 if(action==='notes'){const box=article.querySelector('.owner-notes');box.hidden=!box.hidden;if(box.hidden)openNotes.delete(id);else{openNotes.add(id);box.querySelector('textarea').focus();}return;}
 button.disabled=true;feedback.textContent='';try{
  if(action==='save-notes'){await post('/api/admin/notes',{id,notes:article.querySelector('[data-notes]').value});feedback.textContent='Notes saved. No review requested.';}
  if(action==='review'){const requestId=requests.get(id)||crypto.randomUUID();requests.set(id,requestId);await post('/api/admin/review',{id,requestId,notes:article.querySelector('[data-notes]').value});requests.delete(id);await load();}
  if(action==='save-package'){await post('/api/admin/package',{id:button.dataset.review,text:article.querySelector('[data-package]').value});feedback.textContent='Your edited package is saved.';}
  if(action==='copy-package'){await navigator.clipboard.writeText(article.querySelector('[data-package]').value);feedback.textContent='Copied: cover note, deliverable, and how to use it. Nothing has been sent.';}
 }catch(err){feedback.textContent=err.message;}finally{button.disabled=false;}
});
// Do not interrupt typing or overwrite unsaved local edits when a result arrives.
setInterval(()=>{if(!document.querySelector('#inbox').hidden&&!document.hidden&&!list.contains(document.activeElement))load();},15000);
(async()=>{if(magicToken){document.querySelector('#login').hidden=true;status.textContent='Opening your private inbox…';try{const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:magicToken})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not open this private link.');magicToken=null;if(!await load())document.querySelector('#login').hidden=false;}catch(e){magicToken=null;document.querySelector('#login').hidden=false;status.textContent=e.message;}}else{try{const r=await fetch('/api/admin/leads');if(r.ok)await load();}catch{}}})();
