import {makePreview,EXPERIENCE,SUPPORT,SHARE_URL} from './preview.mjs';
const app=document.querySelector('#app'),friends=location.pathname.replace(/\/$/,'')==='/friends';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={aim:'',experience:'new',supportPreference:'unsure',friction:'',name:'',email:'',consent:false},step='discover',pending=false,receipt=null,requestId=crypto.randomUUID();
const choice=(v,label)=>`<label class="choice"><input type="radio" name="experience" value="${v}" ${state.experience===v?'checked':''}><span>${esc(label)}</span></label>`;
function render(){
 if(step==='discover')app.innerHTML=`<div class="layout"><section><p class="step">${friends?'An invitation from Noah':'Start with your life.'}</p><h1 tabindex="-1">What would you like to get moving?</h1><p class="lead">Something at work. A creative idea. The garage you keep meaning to clear. Tell ${friends?'Noah':'us'} what it is, and see how AI could help.</p><form id="discovery"><label class="field" for="aim">What do you want to do?</label><textarea id="aim" name="aim" required minlength="8" maxlength="1200" placeholder="I want to clean out my garage so I can use it again…">${esc(state.aim)}</textarea><fieldset style="margin-top:24px"><legend>How much have you used AI?</legend><div class="choices">${Object.entries(EXPERIENCE).map(([v,l])=>choice(v,l)).join('')}</div></fieldset><fieldset><legend>What would help you get started?</legend><p class="note">Choose what sounds useful for this task. You can change your mind.</p><div class="choices">${Object.entries(SUPPORT).map(([v,l])=>`<label class="choice"><input type="radio" name="supportPreference" value="${v}" ${state.supportPreference===v?'checked':''}><span>${esc(l)}</span></label>`).join('')}</div></fieldset><label class="field" for="friction">What makes it difficult? <span class="note">Optional</span></label><input id="friction" name="friction" maxlength="600" value="${esc(state.friction)}" placeholder="I do not know where to start."><p class="note">A general description is enough. Leave out private records and other people’s personal information.</p><div class="actions"><button type="submit">Show me what’s possible</button></div></form></section><aside class="field-note"><h2>You do not need to know what to ask AI.</h2><p>Bring the thing you want to do. We’ll help you find a useful way in.</p><p>${friends?'See a preview and send Noah your idea. Just your name, no email or account.':'See a preview, send it to NTG, then book a conversation with Noah.'}</p></aside></div>`;
 if(step==='preview'){
  const p=makePreview(state);
  app.innerHTML=`<p class="step">Here is a place we could start.</p><div class="layout"><section><h1 tabindex="-1">${esc(p.title)}</h1><div class="rail"><p class="session-title">You want to</p><p class="quote">${esc(state.aim)}</p></div><p class="lead">${esc(p.intro)}</p><h2>What we could create together</h2><div class="deliverables">${p.items.map(([t,d],i)=>`<div class="deliverable"><span class="item-number">${i+1}</span><div><h3>${esc(t)}</h3><p>${esc(d)}</p></div></div>`).join('')}</div>${p.id==='space'?'<div class="space-preview" aria-label="A proposed working record"><div>See<small>Check what is there</small></div><div>Decide<small>You choose what happens</small></div><div>Remember<small>Keep the working record</small></div></div>':''}<p class="note">${esc(p.scope)}</p><p>${esc(p.first)}</p><div class="hint"><h3>A way in that suits you</h3><p>${esc(p.supportGuidance)}</p></div><button class="text-button" data-action="edit">Edit what I wrote</button></section><aside class="sheet lead-form"><h2>${friends?'Send this to Noah.':'Let’s talk about yours.'}</h2><p>${esc(p.guidance)}</p><p>${friends?'Noah will get your starting point and decide how to follow up. Use a name he’ll recognize.':'Send your starting point to NTG. We’ll review it before deciding how to help. Then you can book a 20-minute conversation.'}</p><form id="lead"><label class="field" for="name">Your name</label><input id="name" name="name" required maxlength="120" autocomplete="name" value="${esc(state.name)}">${friends?'':`<label class="field" for="email">Email</label><input id="email" name="email" type="email" required maxlength="254" autocomplete="email" value="${esc(state.email)}">`}<div class="honey" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="consent"><input name="consent" type="checkbox" required ${state.consent?'checked':''}><span>${friends?'Send my name and idea to Noah for review and follow-up.':'NTG may review these answers and contact me about this request.'}</span></label><p class="note">${friends?'Your name and answers are stored privately for Noah. No email address is collected.':'Your name, email, and answers are stored privately for this inquiry. No mailing-list signup.'}</p><button type="submit">${friends?'Send my idea to Noah':'Send my starting point to NTG'}</button><p id="submit-status" role="status" aria-live="polite"></p></form></aside></div>`;
 }
 if(step==='sent'){
  const p=makePreview(state);app.innerHTML=`<div class="layout"><section><p class="step success">${friends?'Received for Noah':'Received by NTG'}</p><h1 tabindex="-1">${friends?'Your idea is with Noah.':'Let’s talk about making it happen.'}</h1><p class="lead">${friends?'He’ll review what you sent and decide what to try with you. If you’d like, you can also choose a time to talk.':'Your starting point is in our review inbox. Book a 20-minute conversation with Noah so we can decide what to try together.'}</p><div class="rail"><p class="quote">${esc(state.aim)}</p><p>Possible starting point: ${esc(p.artifact)}.</p></div><a class="button-link" id="booking" href="${esc(receipt.bookingUrl)}" target="_blank" rel="noopener noreferrer">Choose a time with Noah</a><p class="note">${friends?'Booking is optional. Google Calendar asks for an email if you choose to book; your idea has already been submitted without one.':'Opens Google Calendar. Choose a time and complete the booking there. Submitting this form has not booked a meeting or sent a confirmation email.'}</p><p class="note">Reference: <span id="receipt">${esc(receipt.receipt)}</span></p></section><aside class="field-note"><h2>Know someone with a thing they want to do?</h2><p>Send them the starting point. They can explore their own idea without creating an account.</p><button data-action="share" class="secondary">Share this with someone</button><p id="share-status" role="status"></p></aside></div>`;
 }
 window.scrollTo(0,0);app.querySelector('h1')?.focus({preventScroll:true});
}
app.addEventListener('submit',async e=>{
 e.preventDefault();if(pending)return;const d=Object.fromEntries(new FormData(e.target));
 if(e.target.id==='discovery'){Object.assign(state,d);state.aim=state.aim.trim();if(state.aim.length<8){document.querySelector('#aim').setCustomValidity('Add a few words about what you want to do.');document.querySelector('#aim').reportValidity();return;}step='preview';render();return;}
 if(e.target.id!=='lead')return;
 Object.assign(state,{name:d.name.trim(),email:friends?'':d.email.trim(),consent:d.consent==='on'});
 pending=true;const button=e.target.querySelector('button');button.disabled=true;button.textContent='Sending…';const status=document.querySelector('#submit-status');status.textContent='';
 try{const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state,channel:friends?'friends':'public',requestId,website:d.website||''}),signal:AbortSignal.timeout(20000)});let result;try{result=await response.json();}catch{throw new Error('The submission could not be confirmed. Your answers are still here. Please try again.');}if(!response.ok)throw new Error(result.error||'We could not receive your request. Please try again.');if(!result.receipt||!result.bookingUrl)throw new Error('The submission could not be confirmed. Please try again.');receipt=result;step='sent';render();}
 catch(error){status.textContent=error.name==='TimeoutError'?'The connection timed out. Your answers are still here. Try again; the same request will not create a duplicate.':error.message;status.className='error';}
 finally{pending=false;if(document.contains(button)){button.disabled=false;button.textContent=friends?'Send my idea to Noah':'Send my starting point to NTG';}}
});
app.addEventListener('input',e=>{if(e.target.id==='aim')e.target.setCustomValidity('');});
app.addEventListener('click',async e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='edit'&&!pending){const f=document.querySelector('#lead');if(f){const d=Object.fromEntries(new FormData(f));state.name=d.name;state.email=d.email||'';state.consent=d.consent==='on';}step='discover';requestId=crypto.randomUUID();render();}if(action==='share'){const url=friends?SHARE_URL+'friends':SHARE_URL;try{if(navigator.share){await navigator.share({title:'A place to begin',text:'What is one thing you would like to get moving?',url});}else{await navigator.clipboard.writeText(url);document.querySelector('#share-status').textContent='Link copied. Your answers are not included.';}}catch(err){if(err.name!=='AbortError')document.querySelector('#share-status').textContent=url;}}});
function reset(e){e?.preventDefault();if(pending)return;state={aim:'',experience:'new',supportPreference:'unsure',friction:'',name:'',email:'',consent:false};requestId=crypto.randomUUID();step='discover';receipt=null;render();}
if(friends)document.querySelector('.status').textContent='For friends of Noah';
for(const id of ['reset','home'])document.querySelector('#'+id).addEventListener('click',reset);render();
