export const VERSION='lead-discovery-2';
export const EXPERIENCE={new:'I barely use AI',some:'I ask questions or get drafts',regular:'I work with it regularly'};
export const BOOKING_URL='https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2gENCeVyScnao3OQvNSGMSBm9WTzg7IwyDQqziNosn5gow_XOu-FyPUvgoDpVt-YjSHbqZe2sV';
export const SHARE_URL='https://ntg-ai-opportunity.noah-023.workers.dev/';
const recipes=[
 {id:'space',match:/\b(garage|shed|attic|basement|closet|declutter|clutter|clean.?out|clear.?out|tidy|storage|spare room)\b/i,title:'A space you can actually use.',artifact:'A practical space-clearing plan',intro:'AI could help turn a few photos and your goal for the space into a plan you can follow, one small section at a time.',items:[['A map of the space','Possible zones for what stays, what needs a decision, and what can leave once you choose.'],['A sorting sequence','A suggested order that keeps the job manageable, without deciding what matters to you.'],['Your first short session','A small starting area, a time limit, and a clear stopping point.']],first:'We could start with what you want the space to be usable for. Photos are optional; a description is enough.',advanced:'We could also create a reusable inventory and decision rules that help keep the space usable.'},
 {id:'story',match:/\b(photo|photos|photograph|photographs|film|video|storyboard|portfolio|zine|album|documentary|gallery)\b/i,title:'Give your material a shape.',artifact:'A first visual story or project treatment',intro:'AI could help you explore how your material fits together and make a rough version you can react to while keeping the creative choices yours.',items:[['A few distinct directions','Different ways the work could unfold, tied to the audience and feeling you want.'],['A first sequence','A storyboard, image sequence, or rough treatment using the material you choose.'],['A focused next move','The one edit, missing shot, or decision that would move the project forward.']],first:'We could start with a small selection and what you want someone to experience.',advanced:'We could develop a repeatable process for carrying your intent across formats and revisions.'},
 {id:'funding',match:/\b(grant|grants|fundraising|donor|funding|sponsor|proposal)\b/i,title:'Make the case you actually have.',artifact:'An evidence-based outline for your funding work',intro:'AI could help connect the outcome you want to the evidence and requirements, then show you what is still missing.',items:[['The case in clear form','A proposed structure connecting the need, your approach, and the outcome.'],['An evidence checklist','Which claims your material supports and which still need a source or a person.'],['A first section to develop','A small draft to review together, with assumptions kept visible.']],first:'We could begin with one opportunity or goal and material you are allowed to share.',advanced:'We could build a reusable evidence library and a review process for adapting proposals without inventing claims.'},
 {id:'team',match:/\b(team|staff|meeting|board|volunteer|program|community|nonprofit)\b/i,title:'Make the next conversation more useful.',artifact:'A shared decision and action map',intro:'AI could help organize the priorities, disagreements, and unanswered questions so your team has something concrete to work on.',items:[['The decision in view','What needs deciding, why it matters, and which alternatives deserve attention.'],['The missing voices and evidence','Questions that need a real person rather than a confident guess.'],['A next conversation with a purpose','A short agenda and a first action that someone can actually own.']],first:'We could begin with one recurring discussion and the decision that keeps getting stuck.',advanced:'We could design a shared AI working space that carries decisions forward while preserving disagreement.'},
 {id:'travel',match:/\b(trip|travel|vacation|itinerary|holiday|journey)\b/i,title:'Turn the trip into choices you can make.',artifact:'A first itinerary with real tradeoffs',intro:'AI could help compare possible shapes for the trip against your interests, pace, and constraints.',items:[['Two possible routes','Different ways to spend the time, with the compromises made visible.'],['A workable daily rhythm','A draft that leaves room for travel, rest, and the things you care about.'],['A verification list','Prices, opening times, accessibility, and availability to check before booking.']],first:'We could start with your available time and what would make the trip worthwhile.',advanced:'We could build a changeable planning tool that compares alternatives as your constraints change.'},
 {id:'learn',match:/\b(learn|understand|study|practice|skill|lesson)\b/i,title:'Make a first attempt you can learn from.',artifact:'A small learning project built around your goal',intro:'AI could help explain the confusing part, give you a manageable attempt, and adjust the next step to your response.',items:[['A useful starting explanation','An explanation connected to something you already understand.'],['A small working attempt','An exercise or project that makes the skill tangible.'],['Feedback you can use','A way to check your understanding and decide what to try next.']],first:'We could begin with what you want to be able to do and the part that currently stops you.',advanced:'We could build a practice loop with increasingly difficult examples and independent checks.'},
 {id:'writing',match:/\b(write|writing|book|essay|newsletter|speech|presentation|website|blog)\b/i,title:'Give the idea a first form.',artifact:'A structured first draft in your direction',intro:'AI could help sort your material, explore a few structures, and produce a starting draft that you can shape.',items:[['A clear through-line','What you want to say and what the audience needs to take away.'],['A first draft or outline','A concrete starting point based on the material and voice you supply.'],['A useful revision plan','What to clarify, cut, check, or make more specific.']],first:'We could start with who it is for and what you want them to understand.',advanced:'We could develop a repeatable editorial process that preserves your voice and checks claims.'},
 {id:'general',match:/.*/,title:'Give this a concrete first step.',artifact:'A first working plan for the thing you named',intro:'AI could help turn your description into options, a rough first attempt, and a next step small enough to try.',items:[['The outcome in clear form','What you want to be different and what a useful result would look like.'],['A tangible first attempt','A plan, outline, comparison, or sketch we choose to fit your situation.'],['A next step with a purpose','What you can try, what needs checking, and where a person needs to decide.']],first:'We will use the conversation to choose the right form for your situation before creating it.',advanced:'We could explore how the work carries forward across sessions and which parts can be made repeatable.'}
];
export function makePreview({aim,experience}){const text=String(aim||'').trim();const r=recipes.find(r=>r.match.test(text));return {version:VERSION,id:r.id,title:r.title,artifact:r.artifact,intro:r.intro,items:r.items,first:r.first,aim:text,guidance:experience==='new'?'We will walk through it with you. You do not need an AI account or preparation for the conversation.':experience==='regular'?r.advanced:'We will start from what you have tried and look for a more useful way to work with AI.',scope:'This is a preview of what we could create together. We have not analyzed your materials or generated a finished plan.'};}
